### ISSUE TITLE
Feature Request: Adding existing IAM users to and IAM Org

### ISSUE THREAD

**Issue by cramassamy** [philips-software/terraform-provider-hsdp#39]
**Feature Request**
Creating the link between users to and organization is only possible at the user creation.
ressources: **hsdp_iam_org** and **hsdp_iam_user** do not permit to link existing users to an organization.

So ressource **hsdp_iam_org** could accept an array of _user_id_
AND/OR
So ressource **hsdp_iam_user** could accept an array of _organization_id_

Thanks in advance
Cédric Ramassamy

**Comment by loafoe** [comment]
A user can only have one `managing_organization` which is determined at user creation time. This cannot be changed afterwards. The way users inherit permissions in other organizations is through IAM group assignment. This is supported in the provider via the `hsdp_iam_group` resource which has a `user` list field. 

```hcl
resource "hsdp_iam_user" "andy" {
    organization_id = hsdp_iam_org.orgA.id
    ...
}

resource "hsdp_iam_group" "groupX" {
    managing_organization = hsdp_iam_org.orgB.id
    users = [hsdp_iam_user.andy.id]
    ...
}
```

**Comment by cramassamy** [comment]
Thanks Andy,
That is convenient for our needs. 

But then on the IAM UI there is two ways of assigning users to organizations
1) Directly on the org without groups (not supported by current TRM provider)
2) Via groups and roles (supported by TRM)

What is the preferred way generally ?

**Comment by loafoe** [comment]
Hi Cedric,

1. You can create a user under an IAM Org yes. This IAM Org becomes the  users' `managing organization`.  However, no group or role assigned has happened yet for this new user at that point;

2. The next step would be to add the user to one or more groups so they inherit roles assigned to those groups. Through the roles they ultimately gain permissions for that ORG;

3. You can also add users to Groups belonging to other IAM organizations. These users will however not show up under that IAM Orgs user list (1) since they will still be managed by their original managing organization.

The [IAM resource model](https://www.hsdp.io/documentation/identity-and-access-management-iam/concepts/iam-resource-model) goes into more detail about this and has a nice diagram showing the relationships between the different resources.

- User creation (1) is supported by the provider through [`hsdp_iam_user`](https://registry.terraform.io/providers/philips-software/hsdp/latest/docs/resources/iam_user)

- Group assignment (2) is supported by the provider through [`hsdp_iam_group`](https://registry.terraform.io/providers/philips-software/hsdp/latest/docs/resources/iam_group)

So these are two distinct activities. Depending on the mapping and structure of your proposition you may choose to create all users in your  root IAM Org and then do the Group assignment in IAM SubOrgs. Personally I prefer that over creating users under SubOrgs, but it really depends on the solution.

**Comment by loafoe** [comment]
@cramassamy closing this ticket as the requested feature is already available
